# Generated by Django 5.1.7 on 2025-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique='True', verbose_name='Название')),
                ('slug', models.SlugField(blank='True', max_length=200, null='True', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию товара',
                'verbose_name_plural': 'Категории товара',
            },
        ),
    ]
