# Generated by Django 5.1.7 on 2025-04-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=62, unique=True)),
                ('password', models.CharField(max_length=62)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
